// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// HostNetworkConfigApplyConfiguration represents a declarative configuration of the HostNetworkConfig type for use
// with apply.
//
// HostNetworkConfig defines how the FoundationDB pods use the host network.
type HostNetworkConfigApplyConfiguration struct {
	// Enabled defines whether the FoundationDB pods use the host network. When enabled, the operator
	// assigns every pod a unique block of ports from the port range, so that multiple pods of this
	// cluster can run on the same node. Defaults to false.
	Enabled *bool `json:"enabled,omitempty"`
	// PortRangeStart defines the first port of the range the operator assigns port blocks from.
	// Required when Enabled is true.
	PortRangeStart *int `json:"portRangeStart,omitempty"`
	// PortRangeEnd defines the last port (inclusive) of the range the operator assigns port blocks from.
	// Required when Enabled is true.
	PortRangeEnd *int `json:"portRangeEnd,omitempty"`
}

// HostNetworkConfigApplyConfiguration constructs a declarative configuration of the HostNetworkConfig type for use with
// apply.
func HostNetworkConfig() *HostNetworkConfigApplyConfiguration {
	return &HostNetworkConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *HostNetworkConfigApplyConfiguration) WithEnabled(value bool) *HostNetworkConfigApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithPortRangeStart sets the PortRangeStart field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortRangeStart field is set to the value of the last call.
func (b *HostNetworkConfigApplyConfiguration) WithPortRangeStart(value int) *HostNetworkConfigApplyConfiguration {
	b.PortRangeStart = &value
	return b
}

// WithPortRangeEnd sets the PortRangeEnd field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortRangeEnd field is set to the value of the last call.
func (b *HostNetworkConfigApplyConfiguration) WithPortRangeEnd(value int) *HostNetworkConfigApplyConfiguration {
	b.PortRangeEnd = &value
	return b
}
