// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// PortBlockApplyConfiguration represents a declarative configuration of the PortBlock type for use
// with apply.
//
// PortBlock defines a block of consecutive ports used by one pod.
type PortBlockApplyConfiguration struct {
	// Start is the first port of the block.
	Start *int `json:"start,omitempty"`
	// ServersPerPod is the number of fdbserver processes the block holds. The block has
	// 2 * ServersPerPod + 1 ports: a TLS and a non-TLS port per process, and the metrics port.
	ServersPerPod *int `json:"serversPerPod,omitempty"`
}

// PortBlockApplyConfiguration constructs a declarative configuration of the PortBlock type for use with
// apply.
func PortBlock() *PortBlockApplyConfiguration {
	return &PortBlockApplyConfiguration{}
}

// WithStart sets the Start field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Start field is set to the value of the last call.
func (b *PortBlockApplyConfiguration) WithStart(value int) *PortBlockApplyConfiguration {
	b.Start = &value
	return b
}

// WithServersPerPod sets the ServersPerPod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServersPerPod field is set to the value of the last call.
func (b *PortBlockApplyConfiguration) WithServersPerPod(value int) *PortBlockApplyConfiguration {
	b.ServersPerPod = &value
	return b
}
