// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// PortBlocksConfigApplyConfiguration represents a declarative configuration of the PortBlocksConfig type for use
// with apply.
//
// PortBlocksConfig defines the port range that the operator assigns port blocks from.
type PortBlocksConfigApplyConfiguration struct {
	// PortRangeStart defines the first port of the range the operator assigns port blocks from.
	PortRangeStart *int `json:"portRangeStart,omitempty"`
	// PortRangeEnd defines the last port (inclusive) of the range the operator assigns port blocks from.
	PortRangeEnd *int `json:"portRangeEnd,omitempty"`
}

// PortBlocksConfigApplyConfiguration constructs a declarative configuration of the PortBlocksConfig type for use with
// apply.
func PortBlocksConfig() *PortBlocksConfigApplyConfiguration {
	return &PortBlocksConfigApplyConfiguration{}
}

// WithPortRangeStart sets the PortRangeStart field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortRangeStart field is set to the value of the last call.
func (b *PortBlocksConfigApplyConfiguration) WithPortRangeStart(value int) *PortBlocksConfigApplyConfiguration {
	b.PortRangeStart = &value
	return b
}

// WithPortRangeEnd sets the PortRangeEnd field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortRangeEnd field is set to the value of the last call.
func (b *PortBlocksConfigApplyConfiguration) WithPortRangeEnd(value int) *PortBlocksConfigApplyConfiguration {
	b.PortRangeEnd = &value
	return b
}
